### PR TITLE
Add support for ReactPy v2.x

### PR DESCRIPTION
**Pull request by shawncrawley**
## Description

This is my attempt to update reactpy-router to work with the ReactPy v2.0 pre-release package.

## Checklist

Please update this checklist as you complete each item:

-   [x] Tests have been developed for bug fixes or new functionality.
-   [x] The changelog has been updated, if necessary.
-   [x] Documentation has been updated, if necessary.
-   [x] GitHub Issues closed by this PR have been linked.

<sub>By submitting this pull request I agree that all contributions comply with this project's open source license(s).</sub>

### CODE REVIEW

**Comment by shawncrawley** [comment]
When I run the test suite locally, I still have one test failing that I couldn't figure out how to fix: `test_simple_router`. The failure is coming from code that was introduced years ago and hasn't changed since. It's this line here:

https://github.com/reactive-python/reactpy-router/blob/898c8fdd29ccb7487362eff604af426f09d27cc4/tests/test_router.py#L52

It is failing with: `AttributeError: 'DisplayFixture' object has no attribute '_next_view_id'`

I used various AI searches and did a lot of digging to find out how that could have ever worked and thus hopefully discover the required refactor, but unfortunately my searching came up empty.

**Review by Archmonger — APPROVED** [review]
I've fixed all issues within this PR, and have reviewed the changes.

Approved.
